### ISSUE TITLE
Telas de primeira interação do usuário

### ISSUE THREAD

**Issue by GuilhermeEDS** [nathan-vl/dice_keeper#3]

**Comment by GuilhermeEDS** [comment]
![úsuario primeira vez](https://github.com/nathan-vl/dice_keeper/assets/102765171/1719a11a-c234-4f3a-b2e6-eaa0c0becb90)

**Comment by deyvidwms** [comment]
- [ ] Tela de escolha de tipo de usuário
- [ ] Tela de criação de campanha
- [ ] Tela de QRCode
- [ ] Tela de Entrar na Campanha

**Comment by deyvidwms** [comment]
Closes #3
